# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90e70e701b4309c4175a2e033746f168653f242220a98356949b2c4325ac78cc88981741fa6661844f8cac46d223bdad9b4672ee92f0fd7817946f78547e92d2

test:
  secret_key_base: b1e996c966378acdd581e7feb751e304ffbfa6ae29c6a666415695310ccd77848675f2345c2314ceb97a43cd89e395ba49b47525521155a4ebe8fbb0ca6e346f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
